  name: empower_safe
  description: A Flutter app to empower women against violence.
  version: 1.0.0
  environment:
    sdk: '>=2.18.0 <3.0.0'
  dependencies:
    flutter:
      sdk: flutter
    firebase_core: ^3.6.0
    cloud_firestore: ^5.4.3
    firebase_auth: ^5.3.1
    lottie: ^3.1.2
    url_launcher: ^6.3.0
    google_fonts: ^6.2.1
    uuid: ^4.5.0
    path_provider: ^2.1.4
  dev_dependencies:
    flutter_test:
      sdk: flutter
  flutter:
    uses-material-design: true
    assets:
      - assets/animations/welcome_animation.json
      - assets/images/logo.jpeg
