// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKSjgQgeGxi0eRzVzAOnw6k--1Cv0C1w',
    appId: '1:524923631166:web:6ac32d20f1e27c61fdc36f',
    messagingSenderId: '524923631166',
    projectId: 'csp-demo-8f810',
    authDomain: 'csp-demo-8f810.firebaseapp.com',
    storageBucket: 'csp-demo-8f810.firebasestorage.app',
    measurementId: 'G-8H1P3Z1KFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15EzNmTf5OByuHjUqt2qWA2o9XkcIUqQ',
    appId: '1:524923631166:android:ec56b329beb96270fdc36f',
    messagingSenderId: '524923631166',
    projectId: 'csp-demo-8f810',
    storageBucket: 'csp-demo-8f810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDl-mi_6jBEjQ_UScTc2PEJNU-W4XBiE4',
    appId: '1:524923631166:ios:f8ea7d2150ccead2fdc36f',
    messagingSenderId: '524923631166',
    projectId: 'csp-demo-8f810',
    storageBucket: 'csp-demo-8f810.firebasestorage.app',
    iosBundleId: 'com.example.cspDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDl-mi_6jBEjQ_UScTc2PEJNU-W4XBiE4',
    appId: '1:524923631166:ios:f8ea7d2150ccead2fdc36f',
    messagingSenderId: '524923631166',
    projectId: 'csp-demo-8f810',
    storageBucket: 'csp-demo-8f810.firebasestorage.app',
    iosBundleId: 'com.example.cspDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRKSjgQgeGxi0eRzVzAOnw6k--1Cv0C1w',
    appId: '1:524923631166:web:dcd90ded00c85695fdc36f',
    messagingSenderId: '524923631166',
    projectId: 'csp-demo-8f810',
    authDomain: 'csp-demo-8f810.firebaseapp.com',
    storageBucket: 'csp-demo-8f810.firebasestorage.app',
    measurementId: 'G-KWXH47EEZ0',
  );
}
